### ISSUE TITLE
ImportError: No module named mesos

### ISSUE THREAD

**Issue by SamuelMarks** [deric/mesos-deb-packaging#20]
Ubuntu 14.04 LTS x64:
```
$ mesos cat
Traceback (most recent call last):
  File "/usr/bin/mesos-cat", line 12, in <module>
    from mesos import http
ImportError: No module named mesos
```

Same error with `mesos tail`, `mesos ps` and `mesos scp`,

**Comment by deric** [comment]
```
apt-get install python-pip
pip install mesos.cli mesos.interface
```
shoud solve this.

**Comment by SamuelMarks** [comment]
@deric Thanks I'll try that. Also should that and `openjdk-7-jre-headless` be made dependencies of the .deb?

Actually maybe this `pip` stuff more fits under `postinst`?

**Comment by deric** [comment]
The package is completely wrong :smiley:. Standard Debian way would be splitting this into several components like:
-  `libmesos` - just native `libmesos.so` library
- `mesos-master` - just master server, depends on `libmesos`, probably `python` for web UI
- `mesos-slave` - depends on `libmesos`
- `mesos-cli` python packages
- `mesos-java` java binding depends on `libmesos`, `java-runtime-headless`

To answer you question, `java-runtime-headless` is a virtual package that could be provided by:
`default-jre-headless, gcj-4.8-jre-headless, gcj-4.9-jre-headless, gcj-jre-headless, openjdk-7-jre-headless, oracle-java6-installer, oracle-java7-installer, oracle-java8-installer, oracle-java9-installer
`

**Comment by SamuelMarks** [comment]
Ahaha, true that

As recent as August there were whispers on the mailing-list, hopefully someone will package them proper and contribute [official] binaries regularly to official debian+ubuntu repositories.
